language: python
python:
- 3.6
- 3.5
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: aiguofer
  password:
    secure: ov2Q6cwmWImgcdC1aRlBuXzFfMK56XZBQUXa4/O5NBmwgvSDUNIhoMAuD91zdb7JDpgOonydsANZLZkYJeSUlZE0uKRINuebHJQ1wlDJ1aDwFlZ7y5smiHEdYyGp6/PnwqA5zy/CU+4Cq0nsweUTVZusQTttM1umtppHCiEGgQPBXzOFpGPtjaUkdUoxhm3XTXTZQQKwIQr6UpeU6lp40khog2okzCEetNpaWC1WEmzRZlkjQyiwydARsyCGoDs+xP6EJs9NtgVTb7qy8N5Lln3L9hM1o4k+gRlgXD3WgNQR7A3X9NQ4GtgSMX34D1vkOQ0cvQkCMnu0DNGQvg9RQvx+WYpa3PO+DJaiVlIfwlpKrYCt81eMtUnvHrFF5LvpnjygWEW2SE10N/BaHcCfoXd+WEa+4RvbiBNCxV/kY35Ebo/1tHhQIbq9neHXa2oDsIyaBFIU6LCZ6DqGbjoHuRB/RcR4vVUYw38Jg4UcqA1LLOPfzgsdiPAGgS1rDHZz0o0OaM638p3dSF+m5QAZU9iEvRWImem3y81UWByThlUGnSETYAH5UVybYYDt+namFkBuX9FkVGysaPiuCM0kYULB8t6SPozlMEvwYfglb9gOrq6girXEcaZgZ81wGQZdfV4Zvl3U2Mg1UweGApoE9if2sRqc1/j9OMcByRARXxY=
  on:
    tags: true
    repo: aiguofer/sql_connectors
    python: '3.6'
